<Project Sdk="Microsoft.NET.Sdk.Web"><PropertyGroup>  <UserSecretsId>f7282cde-9a5f-4884-afa2-f13c594401e0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeGuardAI.Application\CodeGuardAI.Application.csproj" />
    <ProjectReference Include="..\CodeGuardAI.Infrastructure\CodeGuardAI.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
  </ItemGroup>

</Project>
