// <auto-generated />
using System;
using CodeGuardAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CodeGuardAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CodeGuardDbContext))]
    partial class CodeGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CodeGuardAI.Domain.Observability.AIModelRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_type");

                    b.Property<int>("InputChars")
                        .HasColumnType("integer")
                        .HasColumnName("input_chars");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<int>("OutputChars")
                        .HasColumnType("integer")
                        .HasColumnName("output_chars");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("purpose");

                    b.Property<Guid>("ReviewRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReviewRunId")
                        .HasDatabaseName("ix_ai_model_runs_review_run_id");

                    b.ToTable("ai_model_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_model_runs_non_negative_metrics", "duration_ms >= 0 AND input_chars >= 0 AND output_chars >= 0");
                        });
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Observability.ToolExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("error_type");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("input_summary");

                    b.Property<string>("OutputSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("output_summary");

                    b.Property<Guid?>("ReviewRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("ToolName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tool_name");

                    b.HasKey("Id");

                    b.HasIndex("ReviewRunId")
                        .HasDatabaseName("ix_tool_executions_review_run_id");

                    b.ToTable("tool_executions", null, t =>
                        {
                            t.HasCheckConstraint("ck_tool_executions_non_negative_duration", "duration_ms >= 0");
                        });
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedRootPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_root_path");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("repository_path");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedRootPath")
                        .IsUnique()
                        .HasDatabaseName("ux_projects_normalized_root_path");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Reviews.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("category");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer")
                        .HasColumnName("end_line");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("file_path");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReviewRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_run_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("severity");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer")
                        .HasColumnName("start_line");

                    b.Property<string>("Suggestion")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("suggestion");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ReviewRunId")
                        .HasDatabaseName("ix_findings_review_run_id");

                    b.ToTable("findings", null, t =>
                        {
                            t.HasCheckConstraint("ck_findings_confidence", "confidence >= 0 AND confidence <= 1");

                            t.HasCheckConstraint("ck_findings_line_range", "start_line >= 1 AND end_line >= start_line");
                        });
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Reviews.ReviewRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("error_code");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model_name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("ScanSummaryJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("scan_summary_json");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_review_runs_project_id");

                    b.ToTable("review_runs", (string)null);
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Tests.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReviewRunId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_run_id");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("scenario");

                    b.Property<string>("SuggestedTestCode")
                        .HasColumnType("text")
                        .HasColumnName("suggested_test_code");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("target");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("ReviewRunId")
                        .HasDatabaseName("ix_test_cases_review_run_id");

                    b.ToTable("test_cases", (string)null);
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Observability.AIModelRun", b =>
                {
                    b.HasOne("CodeGuardAI.Domain.Reviews.ReviewRun", null)
                        .WithMany()
                        .HasForeignKey("ReviewRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_model_runs_review_runs_review_run_id");
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Observability.ToolExecution", b =>
                {
                    b.HasOne("CodeGuardAI.Domain.Reviews.ReviewRun", null)
                        .WithMany()
                        .HasForeignKey("ReviewRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_tool_executions_review_runs_review_run_id");
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Reviews.Finding", b =>
                {
                    b.HasOne("CodeGuardAI.Domain.Reviews.ReviewRun", null)
                        .WithMany()
                        .HasForeignKey("ReviewRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_findings_review_runs_review_run_id");
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Reviews.ReviewRun", b =>
                {
                    b.HasOne("CodeGuardAI.Domain.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_runs_projects_project_id");
                });

            modelBuilder.Entity("CodeGuardAI.Domain.Tests.TestCase", b =>
                {
                    b.HasOne("CodeGuardAI.Domain.Reviews.ReviewRun", null)
                        .WithMany()
                        .HasForeignKey("ReviewRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_test_cases_review_runs_review_run_id");
                });
#pragma warning restore 612, 618
        }
    }
}
